/*
  # Ensure session_holds.hold_key is generated by default
  - Backfill any null hold_key values (safety)
  - Set default to gen_random_uuid()
*/

update public.session_holds
  set hold_key = gen_random_uuid()
where hold_key is null;

alter table public.session_holds
  alter column hold_key set default gen_random_uuid();
