name: Supabase Preview
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/commit to preview"
        required: false
        default: feat/rls-rollout-mcp

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: supabase/setup-cli@v1
        with:
          access-token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Start local Supabase (ephemeral)
        run: supabase start | sed -e 's/\(anon key\|service_role key\):.*/\1: <redacted>/'
      - name: Apply migrations
        run: supabase db reset --force
      - name: Generate DB types (optional)
        if: ${{ vars.SUPABASE_PROJECT_ID != '' }}
        run: supabase gen types typescript --project-id $SUPABASE_PROJECT_ID > src/lib/db.types.ts
        env:
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Output local URLs
        run: |
          supabase status
          echo "Preview DB ready (local run). Use with local dev only."
